version: "3.9"  # optional since v1.27.0
services:
  eureka:
    build: ./Eureka-Server
    ports:
      - 9090:8761 
  movie-catalog:
    build: ./movie-catalog-service
    environment: 
   # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    ports:
      - 9093:8081 
    links:
      - eureka
    depends_on:
      - eureka
      - movie-info
      - ratings-info
  movie-info:
    build: ./movie-info-service
    environment: 
   # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    ports:
      - 9094:8082 
    links:
      - eureka
    depends_on:
      - eureka
  ratings-info:
    build: ./ratings-data-service
    environment: 
   # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    ports:
      - 9095:8083 
    links:
      - eureka
    depends_on:
      - eureka
